/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Controladores.*;
import Vista.PruebaChiCuadradoVista;
import Vista.PruebaKolmogorovSmirnovVista;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class PanelGeneradorBasico extends javax.swing.JInternalFrame {

    /**
     * Creates new form PanelGeneradorBasico
     */
    private int prueba;

    public PanelGeneradorBasico(int prueba) {
        initComponents();
        this.prueba = prueba;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSemilla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLimite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFuncionTransicion = new javax.swing.JTextField();
        jTextFieldFuncionSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonEvaluar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Generador Basico");

        jLabel1.setText("Semilla");

        jLabel2.setText("Limite");

        jLabel3.setText("Función de transición");

        jLabel4.setText("Función de Salida");

        jButtonEvaluar.setText("Evaluar");
        jButtonEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEvaluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEvaluar)
                            .addComponent(jTextFieldLimite))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldFuncionTransicion, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextFieldFuncionSalida))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFuncionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEvaluar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEvaluarActionPerformed
        if (revisarCampos()) {
            switch (prueba) {
                case 1:
                    GeneradorBasico GB = new GeneradorBasico(Integer.parseInt(jTextFieldLimite.getText()));
                    GB.setEcuacionSalida(jTextFieldFuncionSalida.getText());
                    GB.setEcuacionTransicion(jTextFieldFuncionTransicion.getText());
                    GB.controlGeneradorBasico(Integer.parseInt(jTextFieldSemilla.getText()));
                    PruebaPromedios PP = new PruebaPromedios();
                    PP.controlPrueba(GB.getFuncionSalida());
                    break;
                case 2:
                    GB = new GeneradorBasico(Integer.parseInt(jTextFieldLimite.getText()));
                    GB.setEcuacionSalida(jTextFieldFuncionSalida.getText());
                    GB.setEcuacionTransicion(jTextFieldFuncionTransicion.getText());
                    GB.controlGeneradorBasico(Integer.parseInt(jTextFieldSemilla.getText()));
                    PruebaVarianza PV = new PruebaVarianza();
                    PV.controlVarianza(GB.getFuncionSalida());
                    break;
                case 3:
                    GB = new GeneradorBasico(Integer.parseInt(jTextFieldLimite.getText()));
                    GB.setEcuacionSalida(jTextFieldFuncionSalida.getText());
                    GB.setEcuacionTransicion(jTextFieldFuncionTransicion.getText());
                    GB.controlGeneradorBasico(Integer.parseInt(jTextFieldSemilla.getText()));
                    PruebaChiCuadrado PCC = new PruebaChiCuadrado(Integer.parseInt(PruebaChiCuadradoVista.jComboBoxGrupos.getSelectedItem().toString()));
                    PCC.control(GB.getFuncionSalida());
                    break;
//                case 4:
//                    GB = new GeneradorBasico(Integer.parseInt(jTextFieldLimite.getText()));
//                    GB.setEcuacionSalida(jTextFieldFuncionSalida.getText());
//                    GB.setEcuacionTransicion(jTextFieldFuncionTransicion.getText());
//                    GB.controlGeneradorBasico(Integer.parseInt(jTextFieldSemilla.getText()));
//                    PruebaKolmogorovSmirnov PKS=new PruebaKolmogorovSmirnov(Integer.parseInt(PruebaKolmogorovSmirnovVista.jComboBoxGrupos.getSelectedItem().toString()));
//                    PKS.Control(GB.getFuncionSalida());
//                    break;
            }
        }
    }//GEN-LAST:event_jButtonEvaluarActionPerformed

    private boolean revisarCampos() {
        String cadena = "Por favor ingrese un dato en los siguientes campos:\n\n";
        int contador = 1;
        boolean check = true;
        if (jTextFieldSemilla.getText().trim().compareToIgnoreCase("") == 0) {
            cadena = cadena + contador + ". Semilla\n";
            contador++;
            check = false;
        }
        if (jTextFieldLimite.getText().trim().compareToIgnoreCase("") == 0) {
            cadena = cadena + contador + ". Limite\n";
            contador++;
            check = false;
        }
        if (jTextFieldFuncionTransicion.getText().trim().compareToIgnoreCase("") == 0) {
            cadena = cadena + contador + ". Función de Transicion\n";
            contador++;
            check = false;
        }
        if (jTextFieldFuncionSalida.getText().trim().compareToIgnoreCase("") == 0) {
            cadena = cadena + contador + ". Función de Salida\n";
            contador++;
            check = false;
        }
        if (cadena.compareToIgnoreCase("Por favor ingrese un dato en los siguientes campos:\n\n") != 0) {
            JOptionPane.showMessageDialog(null, cadena);
        }
        return check;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEvaluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFuncionSalida;
    private javax.swing.JTextField jTextFieldFuncionTransicion;
    private javax.swing.JTextField jTextFieldLimite;
    private javax.swing.JTextField jTextFieldSemilla;
    // End of variables declaration//GEN-END:variables
}
